In [19]:
import pandas as pd

In [20]:
shuffle_df = pd.read_excel('Match_Results.xlsx',
                           sheet_name='Match_Results', engine = 'openpyxl')
rankings_df = pd.read_csv('Rankings.csv')
rankings_df.drop_duplicates(subset=['player'],inplace=True)
rankings_df.set_index(['player'],inplace=True,drop=False)
initial_ranking = 1600
k_factor = 32

In [21]:
def elo_formula(p1_ranking,p2_ranking,p1_score,p2_score,k_factor):
    R1 = 10**(p1_ranking/400)
    R2 = 10**(p2_ranking/400)
    exp_1 = R1/(R1+R2)
    exp_2 = R2/(R1+R2)
    ELO_1 = p1_ranking+k_factor*(p1_score-exp_1)
    ELO_2 = p2_ranking+k_factor*(p2_score-exp_2)
    return ELO_1, ELO_2

In [22]:
shuffle_df

       player1     player2  player1score  player2score      Event
0       Gibian        Dunn             0             1  Summer_21
1        Kayko   Sauchelli             1             0  Summer_21
2     Schleigh     JOBrien             0             1  Summer_21
3        Dargo       Assad             0             1  Summer_21
4      Fratino      Murphy             1             0  Summer_21
5       Dunlap      Uzunic             1             0  Summer_21
6         Papa      Wilson             1             0  Summer_21
7     Kurowska      Burger             1             0  Summer_21
8         Dunn       Kayko             0             1  Summer_21
9      JOBrien       Assad             0             1  Summer_21
10     Fratino      Dunlap             0             1  Summer_21
11        Papa    Kurowska             1             0  Summer_21
12       Kayko       Assad             1             0  Summer_21
13      Dunlap        Papa             1             0  Summer_21
14       Kayko      Dunlap             1             0  Summer_21
15       Kayko       Brown             0             1  Summer_21
16  Goodfellow      Demelo             1             0  Summer_21
17       Merle      Ainley             0             1  Summer_21
18       Kelly   PCzeresko             1             0  Summer_21
19        Ziev   Sochinsky             1             0  Summer_21
20       Weber       Mroue             1             0  Summer_21
21      Hanson    Leggette             0             1  Summer_21
22   Hitchings       Brown             0             1  Summer_21
23    Leonardi    Bakerman             0             1  Summer_21
24  Goodfellow      Ainley             1             0  Summer_21
25       Kelly        Ziev             0             1  Summer_21
26       Weber    Leggette             1             0  Summer_21
27       Brown    Bakerman             1             0  Summer_21
28  Goodfellow        Ziev             0             1  Summer_21
29       Weber       Brown             0             1  Summer_21
30        Ziev       Brown             0             1  Summer_21
31        Ziev      Dunlap             0             1  Summer_21
32    Leggette     POBrien             1             0    Fall_21
33     Chester     Fratino             1             0    Fall_21
34       Olsen   PCzeresko             1             0    Fall_21
35      Dunlap      Gibian             1             0    Fall_21
36        Cole    Witteman             0             1    Fall_21
37   Sauchelli  Buccellato             1             0    Fall_21

In [23]:
#this loop reads the scores in order starting from the top of the matches
#every time you run this loop it will read all of the scores again
for idx in shuffle_df.index:
    player_1 = shuffle_df.player1[idx]
    p1_score = shuffle_df.player1score[idx]
    player_2 = shuffle_df.player2[idx]
    p2_score = shuffle_df.player2score[idx]
    current_rankings_list = list(set(rankings_df.index))
    if player_1 in current_rankings_list:
        p1_ranking = rankings_df.at[player_1,'ranking']
    else:
        p1_ranking = initial_ranking
    if player_2 in current_rankings_list:
        p2_ranking = rankings_df.at[player_2,'ranking']
    else:
        p2_ranking = initial_ranking
    
    ELO_1, ELO_2 = elo_formula(p1_ranking,p2_ranking,p1_score,p2_score,k_factor)
    
    if player_1 in current_rankings_list:
        rankings_df.at[player_1,'ranking'] = ELO_1
    else:
        new_ELO_dict = {'player':player_1,'ranking':ELO_1}
        rankings_df = rankings_df.append(new_ELO_dict, ignore_index=True)
        rankings_df.set_index(['player'],inplace=True,drop=False)
    if player_2 in current_rankings_list:
        rankings_df.at[player_2,'ranking'] = ELO_2
    else:
        new_ELO_dict = {'player':player_2,'ranking':ELO_2}
        rankings_df = rankings_df.append(new_ELO_dict, ignore_index=True)
        rankings_df.set_index(['player'],inplace=True,drop=False)
rankings_df.reset_index(drop=True,inplace=True)
rankings_df.sort_values(by=['ranking'],inplace=True,ascending=False,ignore_index=True)
rankings_df.index+=1
rankings_df.to_csv('Rankings.csv',index=False)

In [24]:
rankings_df.round(1)

        player  ranking
1        Brown     1678
2       Dunlap     1661
3        Kayko     1645
4   Goodfellow     1616
5      Chester     1616
6     Leggette     1616
7     Witteman     1616
8         Papa     1616
9        Weber     1616
10       Assad     1616
11        Ziev     1616
12       Olsen     1615
13    Kurowska     1600
14   Sauchelli     1600
15        Dunn     1600
16    Bakerman     1600
17       Kelly     1600
18      Ainley     1600
19     JOBrien     1600
20     Fratino     1584
21      Demelo     1584
22   Hitchings     1584
23     POBrien     1584
24    Leonardi     1584
25       Merle     1584
26      Murphy     1584
27    Schleigh     1584
28        Cole     1584
29      Burger     1584
30      Hanson     1584
31   Sochinsky     1584
32       Dargo     1584
33      Uzunic     1584
34       Mroue     1584
35      Wilson     1584
36  Buccellato     1583
37      Gibian     1570
38   PCzeresko     1568